FROM continuumio/miniconda3

# Copy the relevant folder into the container
WORKDIR /home
ADD src /home/src
ADD dashboard.py /home/dashboard.py

RUN conda install -c pyviz holoviz
ADD requirements_dashboard.txt /home
RUN pip install -r requirements_dashboard.txt

ENV PORT=8000
EXPOSE $PORT

# Run panel serve to start the app
CMD panel serve --address="0.0.0.0" --port=$PORT dashboard.py
