version: "3.9"

services:

  update_extremes:
    build:
      dockerfile: Dockerfile.preprocessing
      context: .
    env_file:
      - ./.env
    volumes:
      - "./src:/home/src"
    entrypoint: python -m src.preprocess.update_extremes

  make_forecasts:
    build:
      dockerfile: Dockerfile.forecast
      context: .
    env_file:
      - ./.env
    volumes:
      - "./src:/home/src"
    entrypoint: python -m src.forecast.make_forecasts

  dashboard:
    build:
      dockerfile: Dockerfile.dashboard
      context: .
    env_file:
      - ./.env
    volumes:
      - "./src:/home/src"
    entrypoint: python -m dashboard