environment: $ENVIRONMENT|production
vault:
  url: $VAULT_URL|https://enx.vault.schubergphilis.com:8207
  token: $VAULT_TOKEN
  mount_point: $VAULT_MOUNT_POINT|stacks
  stack: $VAULT_PATH_STACK|401-datascience
  path_end: $VAULT_PATH_END|applications/powerbi/default