environment: $ENVIRONMENT|production
vault:
  url: $VAULT_URL|https://enx.vault.schubergphilis.com:8207
  token: $VAULT_TOKEN
  mount_point: $VAULT_MOUNT_POINT|stacks
  stack: $VAULT_PATH_STACK|401-datascience
  athena: $ATHENA|applications/powerbi/default
  snowflake: $SNOWFLAKE|applications/snowflake
snowflake:
  DALI_data:
    database: DB_CDWH_P
    schema: CDWH_4_BDM
    table: BDM_DALI_METINGEN
  DALI_meta:
    database: DB_CDWH_P
    schema: CDWH_5_INF_MEETDATA_E
    table: DIM_DALI_BOX_VW
  DALI_extremes:
    database: DB_DATASCIENCE_P
    schema: DATASCIENCE_1_ETL
    table: DS_SPARK_DALI_WEEK_EXTREMES
  DALI_forecasts:
    database: DB_DATASCIENCE_P
    schema: DATASCIENCE_2_PUBLISH
    table: DS_SPARK_DALI_WEEK_FORECASTS
model:
  n_fourier: 5
  n_polynomial: 2
  fc_horizon: 26
  quantiles: [1, 5, 50, 95, 99]
  tune: 1000
  draws: 1000
