environment: $ENVIRONMENT|production
vault:
  url: $VAULT_URL|https://enx.vault.schubergphilis.com:8207
  token: $VAULT_TOKEN
  mount_point: $VAULT_MOUNT_POINT|stacks
  stack: $VAULT_PATH_STACK|401-datascience
  athena: $ATHENA|applications/powerbi/default
  snowflake: $SNOWFLAKE|applications/snowflake
#athena:
#  database: AwsDataCatalog
#  schema: "enxp401-src-dali"
#  table: enxp401_src_dali_readings
#  boxid: boxid
#  channelid: channelid
#  value: value
#  datetime: timestamp
snowflake:
  database: DB_DATASCIENCE_P
  schema: DATASCIENCE_0_VIEWS
  table: BDM_DALI_METINGEN
#  boxid: BOXID
#  channelid: CHANNELID
#  value: WAARDE
#  datetime: DATUMTIJD